<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-LocalLeadGen.Worker-a1e1c4b4-4143-4e7c-97b9-c667cc8e717d</UserSecretsId>
    <LangVersion>13</LangVersion>
    <NoWarn>$(NoWarn);NU1605;NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LocalLeadGen.Domain\LocalLeadGen.Domain.csproj" />
    <ProjectReference Include="..\LocalLeadGen.Application\LocalLeadGen.Application.csproj" />
    <ProjectReference Include="..\LocalLeadGen.Infrastructure\LocalLeadGen.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
